---
- name: Enable ssh
  hosts: localhost
  become: no
  tasks:
    - pause:
        prompt: "From guest execute: sudo systemctl enable --now sshd"
    - pause:
        prompt: "From host copy ssh key: ssh-copy-id ipedrosa@192.168.122.15"

- name: Install packages
  hosts: debug_vm
  become: yes
  become_method: sudo
  become_user: root
  vars_files:
    - variables.yml

  tasks:
    - name: Install packages
      dnf:
        name: "{{ item }}"
        state: latest
      loop:
        - "{{ packages }}"

- name: Configure services
  hosts: debug_vm
  become: yes
  become_method: sudo
  become_user: root
  vars_files:
    - variables.yml

  tasks:
    - name: Enable services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop: "{{ services }}"

- name: Mount repos
  hosts: debug_vm
  vars_files:
    - variables.yml

  tasks:
    - name: Generate ssh key
      openssh_keypair:
        path: ~/.ssh/id_rsa
        state: present

    - pause:
        prompt: "From guest copy ssh key: ssh-copy-id ipedrosa@192.168.122.1"

    - name: Edit /etc/fuse.conf
      lineinfile:
        path: /etc/fuse.conf
        regexp: '^# user_allow_other'
        line: user_allow_other

    - name: Create repos folder
      file:
        path: "{{ repos_path }}"
        owner: ipedrosa
        group: ipedrosa
        mode: '775'
        state: directory

    - name: Mount remote repos folder
      command: "sshfs -o allow_root -o reconnect {{ username }}@{{ host_ip }}:{{ repos_path }} {{ repos_path }}"
