---
- name: Enable ssh
  hosts: localhost
  become: no
  tasks:
    - pause:
        prompt: "From guest execute: sudo systemctl enable --now sshd"

    - name: Copy ssh key to guest
      command: "ssh-copy-id ipedrosa@192.168.122.15"

- name: Install packages
  hosts: debug_vm
  become: yes
  become_method: sudo
  become_user: root
  vars_files:
    - variables.yml

  tasks:
    - name: Install packages
      dnf:
        name: "{{ packages }}"
        state: latest

- name: Configure guest
  hosts: debug_vm
  become: yes
  become_method: sudo
  become_user: root
  vars_files:
    - variables.yml

  tasks:
    - name: Enable services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop: "{{ services }}"

    - name: Edit /etc/fuse.conf
      lineinfile:
        path: /etc/fuse.conf
        regexp: '^# user_allow_other'
        line: user_allow_other

    - name: Set timezone to Madrid
      timezone:
        name: Europe/Madrid
      notify: Restart crond

  handlers:
    - name: Restart crond
      service:
        name: crond
        state: restarted

- name: Generate ssh key in guest
  hosts: debug_vm
  vars_files:
    - variables.yml

  tasks:
    - name: Generate ssh key
      openssh_keypair:
        path: ~/.ssh/id_rsa
        state: present

    - name: Fetch the keyfile from one server to another
      fetch: 
        src: "~/.ssh/id_rsa.pub"
        dest: "buffer/{{ansible_hostname}}-id_rsa.pub"
        flat: yes

- name: Add guest ssh key to host
  hosts: localhost
  become: no
  vars_files:
    - variables.yml

  tasks:

    - name: Copy the key add to authorized_keys using Ansible module
      authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ lookup('file','buffer/localhost-id_rsa.pub')}}"

- name: Mount repos
  hosts: debug_vm
  become: no
  vars_files:
    - variables.yml

  tasks:

    - name: Authenticate host
      command: "ssh-keyscan {{ host_ip }}"
      register: output

    - name: Add host to known_hosts
      lineinfile:
        path: "{{ home_path }}/.ssh/known_hosts"
        line: "{{ output['stdout'] }}"
        create: yes

    - name: Create repos folder
      file:
        path: "{{ repos_path }}"
        owner: ipedrosa
        group: ipedrosa
        mode: '775'
        state: directory

    - name: Add repos to /etc/fstab
      lineinfile:
        path: /etc/fstab
        #Source: https://superuser.com/questions/669287/automount-sshfs-using-fstab-without-mount-a
        line: "{{ username }}@{{ host_ip }}:{{ repos_path }}  {{ repos_path }}  fuse.sshfs x-systemd.automount,_netdev,user,idmap=user,transform_symlinks,identityfile={{ home_path }}/.ssh/id_rsa,allow_other,default_permissions,uid={{ id }},gid={{ id }} 0 0"
      become: yes
      become_method: sudo
      become_user: root
