---
- name: Enable ssh
  hosts: localhost
  become: no
  tasks:
    - pause:
        prompt: "From guest execute: sudo systemctl enable --now sshd"
    - pause:
        prompt: "From host copy ssh key: ssh-copy-id ipedrosa@192.168.122.15"

- name: Install packages
  hosts: debug_vm
  become: yes
  become_method: sudo
  become_user: root
  vars_files:
    - variables.yml

  tasks:
    - name: Install packages
      dnf:
        name: "{{ item }}"
        state: latest
      loop:
        - "{{ packages }}"

- name: Configure services
  hosts: debug_vm
  become: yes
  become_method: sudo
  become_user: root
  vars_files:
    - variables.yml

  tasks:
    - name: Enable services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop: "{{ services }}"
